.PHONY: up down alembic-upgrade alembic-create-revision

# Start all services in background and build images
up:
	docker compose up -d --build

# Stop all services and clean up containers
down:
	docker compose down

# Apply all pending migrations inside the running backend container
alembic-upgrade:
	docker compose exec backend alembic upgrade head

# Create an autogenerated database migration.
# Usage: make alembic-create-revision m="your_migration_name"
alembic-create-revision:
	@if [ -z "$(m)" ]; then \
		echo "Error: Migration description is required."; \
		echo "Usage: make alembic-create-revision m=\"migration_name\""; \
		exit 1; \
	fi
	docker compose exec backend alembic revision --autogenerate -m "$(m)"
