.PHONY: up down restart ps logs migrate migration db-dump db-reset db-shell clean load-test-menu load-test-order load-test-menu-local load-test-order-local test test-local

# Start all services in the background and build/rebuild container images
up:
	docker compose up -d --build

# Stop all services and remove containers
down:
	docker compose down

# Restart all services
restart:
	docker compose restart

# Show status of all containers
ps:
	docker compose ps

# View real-time logs of all services
logs:
	docker compose logs -f

# Apply all pending database migrations (Alembic)
migrate:
	docker compose exec backend alembic upgrade head

# Create an autogenerated database migration.
# Usage: make migration m="description"
migration:
	@if [ -z "$(m)" ]; then \
		echo "Error: Migration description is required."; \
		echo "Usage: make migration m=\"migration_name\""; \
		exit 1; \
	fi
	docker compose exec backend alembic revision --autogenerate -m "$(m)"

# Dump the current database state to dumps/dump.sql
db-dump:
	@mkdir -p dumps
	docker compose exec -T db pg_dump -U postgres -d table_reservation --clean --if-exists > dumps/dump.sql
	@echo "Dump saved to dumps/dump.sql"

# Reset the database: drop and recreate from dumps/dump.sql
db-reset:
	@if [ ! -f dumps/dump.sql ]; then \
		echo "Error: dumps/dump.sql not found. Run 'make db-dump' first."; \
		exit 1; \
	fi
	docker compose stop backend
	docker compose exec -T db psql -U postgres -d postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'table_reservation' AND pid <> pg_backend_pid();"
	docker compose exec -T db psql -U postgres -d postgres -c "DROP DATABASE IF EXISTS table_reservation;"
	docker compose exec -T db psql -U postgres -d postgres -c "CREATE DATABASE table_reservation OWNER postgres;"
	docker compose exec -T db psql -U postgres -d table_reservation < dumps/dump.sql
	docker compose start backend
	@echo "Database restored from dumps/dump.sql"

db-shell: ## Enter Postgres shell
	docker compose exec db psql -U postgres -d table_reservation

# Stop containers and completely wipe database and MinIO volumes (Factory Reset)
clean:
	docker compose down -v

# Variables for load testing (concurrency and target URL)
c ?= 500
url ?= http://localhost:8000

# Run load test for GET /api/menu_items (inside container)
load-test-menu:
	docker compose exec -T backend python scripts/load_test.py menu --concurrency $(c) --url $(url)

# Run load test for POST /api/food_baskets/{id} (inside container)
load-test-order:
	docker compose exec -T backend python scripts/load_test.py order --concurrency $(c) --url $(url)

# Run load test for GET /api/menu_items (locally on host)
load-test-menu-local:
	python backend/scripts/load_test.py menu --concurrency $(c) --url $(url)

# Run load test for POST /api/food_baskets/{id} (locally on host)
load-test-order-local:
	python backend/scripts/load_test.py order --concurrency $(c) --url $(url)

# Run pytest tests inside docker container
test:
	docker compose exec -T backend pytest tests

# Run pytest tests locally on host
test-local:
	PYTHONPATH=backend uv run --project backend pytest backend/tests


