"""add_image_path_to_food_place_and_menu_item

Revision ID: 09a1890bc5ad
Revises: 1e1fd8c005c6
Create Date: 2026-06-14 15:56:32.364313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a1890bc5ad'
down_revision: Union[str, None] = '1e1fd8c005c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
