"""add_image_path

Revision ID: 1e1fd8c005c6
Revises: 5d870598c120
Create Date: 2026-06-14 14:51:20.586568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1fd8c005c6'
down_revision: Union[str, None] = '5d870598c120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_places', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('menu_items', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'image_path')
    op.drop_column('food_places', 'image_path')
    # ### end Alembic commands ###
