"""add_fields_to_food_basket

Revision ID: 5d870598c120
Revises: 67a2a062d204
Create Date: 2026-06-14 14:28:19.951240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d870598c120'
down_revision: Union[str, None] = '67a2a062d204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_baskets', sa.Column('order_type', sa.String(), nullable=True))
    op.add_column('food_baskets', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('food_baskets', sa.Column('address', sa.String(), nullable=True))
    op.add_column('food_baskets', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_baskets', 'status')
    op.drop_column('food_baskets', 'address')
    op.drop_column('food_baskets', 'phone')
    op.drop_column('food_baskets', 'order_type')
    # ### end Alembic commands ###
