"""add_is_active_to_menu_items_and_delivery_time_to_baskets

Revision ID: f0ca41960823
Revises: c3d4e5f6g7h8
Create Date: 2026-06-20 21:27:33.984840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ca41960823'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_baskets', sa.Column('delivery_time', sa.Time(), nullable=True))
    op.add_column('menu_items', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_active')
    op.drop_column('food_baskets', 'delivery_time')
    # ### end Alembic commands ###
